// Central question bank exported for use by the app.
// Move or extend questions here instead of editing App.jsx directly.
const QUESTIONS = [
  { id: 'SI_01', text: "Hello, please briefly introduce yourself and summarize your academic or work experience in the data field up to now." },
  { id: 'IN_01', text: "Why did you choose to apply for this position/field? In your opinion, what is the most important skill you possess that gives you confidence you will succeed in this role?" },
  { id: 'IN_02', text: "What motivates you to apply to our company? What unique value do you think you can contribute compared to other candidates?" },
  { id: 'IN_03', text: "Can you share some of the projects you have worked on? What skills did you develop from those projects?" },
  { id: 'DF_01', text: "Explain the difference between Mean and Median. When is using the Median more appropriate?" },
  { id: 'DF_02', text: "What does “ data cleaning ” mean in your understanding? Why does it often take the most time?" },
  { id: 'DF_03', text: "Why do we convert raw tables into charts/graphs? What is the main purpose?" },
  { id: 'DF_04', text: "What does the phrase “ Garbage In, Garbage Out ” mean in the data field?" },
  { id: 'DF_05', text: "When should you store data in a database (like SQL) instead of a regular Excel file?" },
  { id: 'DF_06', text: "What are missing values (Missing Value/Null), and how can they harm analysis results?" },
  { id: 'DF_07', text: "What is the significance level (alpha) in hypothesis testing?" },
  { id: 'DF_08', text: "In a dataset, what do we mean when we say a value is an outlier?" },
  { id: 'DF_09', text: "Explain the t-distribution and its relationship with the normal distribution." },
  { id: 'DF_10', text: "What is structured data? Give an example." },
  { id: 'DF_11', text: "What is a CSV file, and why is it popular for data exchange?" },
  { id: 'DF_12', text: "Why must we mask or encrypt sensitive information like phone numbers or ID numbers when analyzing customer data?" },
  { id: 'DF_13', text: "How is real-time data different from historical data?" },
  { id: 'DF_14', text: "What is SQL, and what does it stand for?" },
  { id: 'DF_15', text: "Do you believe data always reflects the truth 100%? Why or why not?" },
  { id: 'DF_16', text: "What is sampling? Why do we sometimes analyze only a subset of the data instead of the entire dataset?" },
  { id: 'DF_17', text: "In machine learning, what does it mean when a model is overfitting?" },
  { id: 'DF_18', text: "What is the central limit theorem and why is it significant in statistics?" },
  { id: 'DF_19', text: "How does calling an API to retrieve weather data work?" },
  { id: 'DF_20', text: "What makes a feature good or poor? Name three characteristics of a good feature." },
  { id: 'PS_01', text: "You receive a customer dataset where the “Age” column is missing for 30% of the rows. How would you handle this? Would you delete those rows or fill in an estimated value" },
  { id: 'PS_02', text: "Your manager informs you that this month’s sales suddenly dropped by 20%. What data would you check first to identify the cause?" },
  { id: 'PS_03', text: "You receive two reports from two different departments about the same metric, but the numbers do not match. What would you do to determine which one is correct?" },
  { id: 'PS_04', text: "When plotting revenue, you notice a row with a negative value (e.g., -$100), which is impossible. How would you handle this data point?" },
  { id: 'PS_05', text: "While cleaning customer data, you find the same person recorded with multiple name variations (e.g., “Nguyễn V. A”, “Nguyễn Văn A”, “Nguyen Van A”). How would you resolve this?" },
  { id: 'PS_06', text: "You want to compare the income distribution of three different customer groups. Which type of chart would you choose (bar chart, pie chart, boxplot)? Why?" },
  { id: 'PS_07', text: "Before analyzing customer behavior data, why is it important to start with a hypothesis (e.g., “Female customers spend more than male customers”)?" },
  { id: 'PS_08', text: "You trained a machine learning model, but it performs very well on the training set and poorly on the test set. What would you check or change?" },
  { id: 'PS_09', text: "Although Excel is powerful, what major limitations does it have when working with very large datasets?" },
  { id: 'PS_10', text: "A report shows that the customer satisfaction rate is 105%. What is your first reaction, and what would you check?" },
  { id: 'PS_11', text: "Your manager asks you to summarize a sensitive company dataset. Should you copy and paste the entire dataset into ChatGPT? Why or why not?" },
  { id: 'PS_12', text: "During data preprocessing, you find several outliers that heavily affect your model. How would you decide whether to remove or keep them?" },
  { id: 'PS_13', text: "If AI provides an analytical insight completely opposite to your intuition, would you trust it immediately? What would you do next?" },
  { id: 'PS_14', text: "You find that sunglasses sales and ice-cream sales increase at the same time. Do you think one causes the other? If not, how would you explain this pattern to your team?" },
  { id: 'PS_15', text: "Given a choice between “a huge amount of messy, inaccurate data” and “a small amount of very clean, accurate data”, which would you choose for building a report? Why?" },
  { id: 'PS_16', text: "Facebook revenue grew 50% while website revenue grew only 10%. Your boss wants to shift all the budget to Facebook. What absolute numbers should you check before agreeing?" },
  { id: 'SS_01', text: "When someone points out a mistake or weakness in your work, how do you respond?" },
  { id: 'SS_02', text: "Are you comfortable working alone for long periods when focusing on research or analysis?" },
  { id: 'SS_03', text: "What ethical principles should a data professional follow when handling users’ personal information?" },
  { id: 'SS_04', text: "How would you explain a complex technical idea to someone with no technical background in a simple and engaging way?" },
  { id: 'SS_05', text: "If project requirements change suddenly midway through the process, how easily can you adapt and adjust your plan?" },
  { id: 'SS_06', text: "Describe a time when you had to process data under very tight deadlines. How did you ensure both speed and accuracy?" },
  { id: 'SS_07', text: "Since 80% of data work involves cleaning and preparation - which can be repetitive and boring - do you think you have the patience to do this long-term?" },
  { id: 'SS_08', text: "How do you avoid getting too deep into minor details and losing sight of the main objective of an analysis?" },
  { id: 'SS_09', text: "Do you prefer working independently for deep analysis, or working in a team to discuss and discover insights together? Why?" },
  { id: 'SS_10', text: "What personal qualities do you think a data professional should have?" },
  { id: 'SS_11', text: "Data roles require high precision, down to decimal points. What habits do you have to double-check your results before submitting them?" }
];

export default QUESTIONS;
