from pydantic import BaseModel, Field
from typing import List, Optional

# --- Authentication and User Models ---

class TokenVerificationRequest(BaseModel):
    """Model for the Interviewee login request."""
    token: str = Field(..., description="The unique session token provided to the interviewee.")
    user_name: str = Field(..., description="The name entered by the interviewee.")

class SessionStartRequest(BaseModel):
    """Model for initiating a new interview session."""
    token: str
    user_name: str
    # Note: The server should generate the folder name and return it.

# --- Interviewer Request Model ---
class InterviewerCreateSessionRequest(BaseModel):
    """Model for the Interviewer to create a new session."""
    interviewee_name: str = Field(..., description="The full name of the candidate for the session.")
    interviewer_id: str = Field(..., description="The UID of the interviewer creating the session.")
    # The token itself will be generated by the server.

# --- Database Models (Question Bank) ---

class Question(BaseModel):
    """Schema for a single question in the bank."""
    id: str = Field(..., description="Unique ID for the question (e.g., QID_001).")
    text: str = Field(..., description="The full text of the question.")
    topic: str = Field(..., description="The category (e.g., Problem Solving).")
    is_active: bool = Field(True, description="Whether the question is currently active for selection.")

# --- Database Models (Interviewer/Session Management) ---

class IntervieweeSession(BaseModel):
    """Schema for an active or completed interview session."""
    token: str = Field(..., description="The unique access token for this session.")
    interviewee_name: str
    interviewer_id: str = Field(..., description="The Firebase UID of the interviewer who created the session.")
    folder_name: Optional[str] = Field(None, description="The DD_MM_YYYY_... folder name on the server.")
    status: str = Field("pending", description="Current status (pending, active, complete, failed).")
    questions_selected: Optional[List[str]] = Field(None, description="List of QIDs selected for this interview.")
    created_at: Optional[str] = Field(None, description="ISO 8601 timestamp of creation.")
    updated_at: Optional[str] = Field(None, description="ISO 8601 timestamp of last update.")

# Note: More models for the Interviewer side (e.g., creating accounts) will be added later.
